// <auto-generated />
using System;
using System.Collections.Generic;
using LudaFit.Infrastructure.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LudaFit.Infrastructure.SQLite.Migrations
{
    [DbContext(typeof(LudaFitDbContext))]
    [Migration("20260403233022_ChangeBookingEntity")]
    partial class ChangeBookingEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("LudaFit.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FoodWeighing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("ClientContacts", "LudaFit.Domain.Entities.Booking.ClientContacts#ClientContacts", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientEmail");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientPhoneNumber");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ClientFoodPreferences", "LudaFit.Domain.Entities.Booking.ClientFoodPreferences#ClientFoodPreferences", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FavoriteFoods")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientFavoriteFoods");

                            b1.Property<string>("UnfavoriteFoods")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientUnfavoriteFoods");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ClientHealth", "LudaFit.Domain.Entities.Booking.ClientHealth#ClientHealth", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Allergies")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientAllergies");

                            b1.Property<bool>("AnxietyTendency")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ClientAnxietyTendency");

                            b1.Property<string>("FeelingUnwellComplaints")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientFeelingUnwellComplaints");

                            b1.Property<string>("Intolerances")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientIntolerances");

                            b1.Property<string>("PhysicalActivities")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientPhysicalActivities");

                            b1.Property<string>("StressAndHowYouCopeWithIt")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientStressAndHowYouCopeWithIt");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ClientMetrics", "LudaFit.Domain.Entities.Booking.ClientMetrics#ClientMetrics", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<uint>("Age")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ClientAge");

                            b1.Property<uint>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ClientHeight");

                            b1.Property<uint>("WaistSize")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ClientWaistSize");

                            b1.Property<float>("Weight")
                                .HasColumnType("REAL")
                                .HasColumnName("ClientWeight");
                        });

                    b.HasKey("Id");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Percent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("DateRange", "LudaFit.Domain.Entities.Discount.DateRange#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndDate");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartDate");
                        });

                    b.HasKey("Id");

                    b.ToTable("Discounts", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Medicines", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("WorkTime", "LudaFit.Domain.Entities.Specialist.WorkTime#TimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("WorkTimeEnd");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("WorkTimeStart");
                        });

                    b.HasKey("Id");

                    b.ToTable("Specialists", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Booking", "Booking")
                        .WithMany("_diagnoses")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Diagnosis", "Diagnosis")
                        .WithMany("Medicines")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Service", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Discount", "Discount")
                        .WithMany("_services")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Booking", b =>
                {
                    b.Navigation("_diagnoses");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Diagnosis", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Discount", b =>
                {
                    b.Navigation("_services");
                });
#pragma warning restore 612, 618
        }
    }
}
