// <auto-generated />
using System;
using System.Collections.Generic;
using LudaFit.Infrastructure.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LudaFit.Infrastructure.SQLite.Migrations
{
    [DbContext(typeof(LudaFitDbContext))]
    partial class LudaFitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("LudaFit.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalActivities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("ClientContacts", "LudaFit.Domain.Entities.Booking.ClientContacts#ClientContacts", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientEmail");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientPhoneNumber");

                            b1.Property<string>("TelegramTag")
                                .HasColumnType("TEXT")
                                .HasColumnName("ClientTelegramTag");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ClientMetrics", "LudaFit.Domain.Entities.Booking.ClientMetrics#ClientMetrics", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<uint>("Age")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ClientAge");

                            b1.Property<uint>("Height")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ClientHeight");

                            b1.Property<uint>("WaistSize")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ClientWaistSize");

                            b1.Property<float>("Weight")
                                .HasColumnType("REAL")
                                .HasColumnName("ClientWeight");
                        });

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Diagnoses", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Percent")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty<Dictionary<string, object>>("DateRange", "LudaFit.Domain.Entities.Discount.DateRange#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("EndDate");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("StartDate");
                        });

                    b.HasKey("Id");

                    b.ToTable("Discounts", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.EmailOutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("AttemptsCount", "NextAttemptAtUtc");

                    b.ToTable("EmailOutboxMessages", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Medicines", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.SocialNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.ToTable("SocialNetworks", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("WorkTime", "LudaFit.Domain.Entities.Specialist.WorkTime#TimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("WorkTimeEnd");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("WorkTimeStart");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialists", (string)null);
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Booking", b =>
                {
                    b.OwnsOne("LudaFit.Domain.ValueObjects.ClientAdditionalInformation", "ClientAdditionalInformation", b1 =>
                        {
                            b1.Property<int>("BookingId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("FoodWeighing")
                                .HasColumnType("INTEGER")
                                .HasColumnName("FoodWeighing");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.OwnsOne("LudaFit.Domain.ValueObjects.ClientFoodPreferences", "ClientFoodPreferences", b2 =>
                                {
                                    b2.Property<int>("ClientAdditionalInformationBookingId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("FavoriteFoods")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ClientFavoriteFoods");

                                    b2.Property<string>("UnfavoriteFoods")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ClientUnfavoriteFoods");

                                    b2.HasKey("ClientAdditionalInformationBookingId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientAdditionalInformationBookingId");
                                });

                            b1.OwnsOne("LudaFit.Domain.ValueObjects.ClientHealth", "ClientHealth", b2 =>
                                {
                                    b2.Property<int>("ClientAdditionalInformationBookingId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Allergies")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ClientAllergies");

                                    b2.Property<bool>("AnxietyTendency")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("ClientAnxietyTendency");

                                    b2.Property<string>("FeelingUnwellComplaints")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ClientFeelingUnwellComplaints");

                                    b2.Property<string>("Intolerances")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ClientIntolerances");

                                    b2.Property<string>("StressAndHowYouCopeWithIt")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ClientStressAndHowYouCopeWithIt");

                                    b2.HasKey("ClientAdditionalInformationBookingId");

                                    b2.ToTable("Bookings");

                                    b2.WithOwner()
                                        .HasForeignKey("ClientAdditionalInformationBookingId");
                                });

                            b1.Navigation("ClientFoodPreferences")
                                .IsRequired();

                            b1.Navigation("ClientHealth")
                                .IsRequired();
                        });

                    b.Navigation("ClientAdditionalInformation");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Booking", "Booking")
                        .WithMany("_diagnoses")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.EmailOutboxMessage", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Booking", "Booking")
                        .WithOne()
                        .HasForeignKey("LudaFit.Domain.Entities.EmailOutboxMessage", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Diagnosis", "Diagnosis")
                        .WithMany("_medicines")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Service", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Discount", "Discount")
                        .WithMany("_services")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.SocialNetwork", b =>
                {
                    b.HasOne("LudaFit.Domain.Entities.Specialist", "Specialist")
                        .WithMany("_socialNetworks")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Booking", b =>
                {
                    b.Navigation("_diagnoses");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Diagnosis", b =>
                {
                    b.Navigation("_medicines");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Discount", b =>
                {
                    b.Navigation("_services");
                });

            modelBuilder.Entity("LudaFit.Domain.Entities.Specialist", b =>
                {
                    b.Navigation("_socialNetworks");
                });
#pragma warning restore 612, 618
        }
    }
}
